### ISSUE TITLE
Start tracking time

### ISSUE THREAD

**Issue by rsaimanjunathnaik** [rsaimanjunathnaik/quiet-boundary-1362#3]
- [x] CSS part(10mins)
- [x] Heading tags (30mins)
- [x] Signup with google(30mins)
- [x]  Logo desiging part
